% VERY IMPORTANT: You need to import Dynamicwind xlsx DATA and t values set
% on NUMERIC MATRIX otherwise this will not work
% Auto-generated by MATLAB on 06-Dec-2021 22:38:41

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Dynamic_wind";
opts.DataRange = "B2:C119944";

% Specify column names and types
opts.VariableNames = ["data", "t"];
opts.VariableTypes = ["double", "double"];

% Import the data  IMPORTANT: THIS LOCATION SHOULD BE WHERE YOUR DATA LOCATED
Dynamicwind = readtable("C:\Users\JVong\Documents\MATLAB\Project\Dynamic_wind.xlsx", opts, "UseExcel", false);

%% Convert to output type
Dynamicwind = table2array(Dynamicwind);

%%
% part 1
voltage = Dynamicwind(:,1);
t =  Dynamicwind(:,2);

% part 2 
% (volts)
cal_volts=[1.1334761517302536, 1.2168838402316453, 1.2574484652661773, 1.28406653483074, 1.2945098977285117, 1.306963086494241, 1.3147604417015477, 1.3228523686035325, 1.3311519051962617, 1.3343771944501273]; 
% (m/s) 
cal_speed=[0,.31,.53,.68,.73,.84,.90,.96,1.02,1.10]; 

P = polyfit(cal_volts,cal_speed,1);

% part 3 
V = polyval(P,voltage);

% part 4 
T = t(length(t))-t(1);

% part 5 
TIME = linspace(0,T,length(t));

% part 6 
plot(TIME,V);

% part 7,8 
Fs = 1/(TIME(2)-TIME(1));
Tf = 1/Fs;
L = T*1000;
tf = (0:L-1)*Tf;

Y = fft(V)/L;

% part 9 loglog scale??

